[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF book/ netlify.toml"

[[redirects]]
  from = "/v0.2/*"
  to = "https://release-v0-2.docs.mun-lang.org/:splat"
  status = 200

[[redirects]]
  from = "/v0.3/*"
  to = "https://release-v0-3.docs.mun-lang.org/:splat"
  status = 200
