[workspace]
name = "mun"
version = "0.6.0-dev"
description = "Development environment for the Mun programming language"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
llvmdev = "14.*"
rust = "1.86.*"
cmake = ">=3.22"
ninja = ">=1.10"

[tasks]
build = "cargo build --workspace"
build-release = "cargo build --workspace --release"
check = "cargo check --all-targets"
test = "cargo test --workspace"
