parameters:
  rust_version: stable

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
    submodules: true

  - template: azure-install-rust.yml

  - template: azure-install-llvm.yml

  - script: cargo check 
    displayName: Check features

  - ${{ if parameters.benches }}:
    - script: cargo check --benches --all
      displayName: Check benchmarks