parameters:
  rust: stable

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }} +${{parameters.rust}}
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-18.04

      ${{ if parameters.cross }}:
        MacOS:
          vmImage: macOS-10.13
        Windows:
          vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)

  steps:
  - checkout: self
    submodules: true

  - template: azure-install-rust.yml
    parameters: 
      rust: ${{ parameters.rust }}

  - template: azure-install-llvm.yml

  - script: |
      echo %PATH%
      cargo test -- --test-threads=1
    env:
      LOOM_MAX_DURATION: 10
      CI: 'True'
    displayName: cargo test