jobs:
- template: azure-test.yml
  parameters:
    displayName: cargo test
    name: cargo_test_stable
    cross: true 
    rust: stable

- template: azure-test.yml
  parameters:
    displayName: cargo test
    name: cargo_test_beta
    rust: beta

- template: azure-test.yml
  parameters:
    displayName: cargo test
    name: cargo_test_nightly
    rust: nightly