name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libudev-dev

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          cache: true
          frozen: true

      - uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: pixi run check

  test:
    name: Test Rust
    runs-on: ${{ matrix.os }}
    needs: check
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "windows-latest", "macos-15-intel"]
        include:
          - RUSTFLAGS: "-Dwarnings"
            CARGO_INCREMENTAL: 1
            CARGO_TARGET_DIR: "target"
          - os: "windows-latest"
            RUSTFLAGS: "-Dwarnings -Ctarget-feature=+crt-static"
            CARGO_INCREMENTAL: 0
            CARGO_TARGET_DIR: "C:\\cargo-target-dir"
          - os: "macos-15-intel"
            MACOSX_DEPLOYMENT_TARGET: "15.5"
            DYLD_FALLBACK_LIBRARY_PATH: "${{ github.workspace }}/.pixi/envs/default/lib"
    env:
      RUSTFLAGS: ${{ matrix.RUSTFLAGS }}
      CARGO_INCREMENTAL: ${{ matrix.CARGO_INCREMENTAL }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.MACOSX_DEPLOYMENT_TARGET }}
      DYLD_FALLBACK_LIBRARY_PATH: ${{ matrix.DYLD_FALLBACK_LIBRARY_PATH }}
      # Disable generating debug info, we don't need it here anyway and its only using disk space
      CARGO_PROFILE_DEV_DEBUG: 0
      CARGO_TARGET_DIR: ${{ matrix.CARGO_TARGET_DIR }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install packages
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libudev-dev

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          cache: true
          frozen: true

      - uses: Swatinem/rust-cache@v2
        if: matrix.os != 'windows-latest'

      - name: Test with coverage
        run: pixi run test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: lcov.info
          name: ${{ matrix.os }}
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  doctest:
    name: Doctest Rust
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "windows-latest", "macos-15-intel"]
        include:
          - RUSTFLAGS: "-Dwarnings"
            CARGO_INCREMENTAL: 1
          - os: "windows-latest"
            RUSTFLAGS: "-Dwarnings -Ctarget-feature=+crt-static"
            CARGO_INCREMENTAL: 0
          - os: "macos-15-intel"
            MACOSX_DEPLOYMENT_TARGET: "15.5"
            DYLD_FALLBACK_LIBRARY_PATH: "${{ github.workspace }}/.pixi/envs/default/lib"
    env:
      RUSTFLAGS: ${{ matrix.RUSTFLAGS }}
      CARGO_INCREMENTAL: ${{ matrix.CARGO_INCREMENTAL }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.MACOSX_DEPLOYMENT_TARGET }}
      DYLD_FALLBACK_LIBRARY_PATH: ${{ matrix.DYLD_FALLBACK_LIBRARY_PATH }}
      # Disable generating debug info, we don't need it here anyway and its only using disk space
      CARGO_PROFILE_DEV_DEBUG: 0
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install packages
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libudev-dev

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          cache: true
          frozen: true

      - uses: Swatinem/rust-cache@v2

      - name: Doctests
        run: pixi run doctest

  test-mdbook:
    name: Test mdbook
    runs-on: ubuntu-22.04
    needs: check
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          cache: true
          frozen: true

      - uses: Swatinem/rust-cache@v2

      - name: Cargo build
        run: pixi run build-runtime

      - name: mdbook test
        run: pixi run mdbook test book -L target/debug/deps

      - name: mdbook build
        run: pixi run mdbook build book

  test-cpp:
    name: Test C++ Runtime
    runs-on: ${{ matrix.os }}
    needs: check
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "windows-latest", "macos-15-intel"]
        include:
          - RUSTFLAGS: "-Dwarnings"
          - os: "windows-latest"
            RUSTFLAGS: "-Dwarnings -Ctarget-feature=+crt-static"
          - os: "macos-15-intel"
            MACOSX_DEPLOYMENT_TARGET: "15.5"
            DYLD_FALLBACK_LIBRARY_PATH: "${{ github.workspace }}/.pixi/envs/default/lib"
    env:
      RUSTFLAGS: ${{ matrix.RUSTFLAGS }}
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.MACOSX_DEPLOYMENT_TARGET }}
      DYLD_FALLBACK_LIBRARY_PATH: ${{ matrix.DYLD_FALLBACK_LIBRARY_PATH }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          cache: true
          frozen: true

      - uses: Swatinem/rust-cache@v2

      - name: Cargo build
        run: pixi run build-capi

      - name: Configure CMake (debug)
        run: pixi run cmake -DCMAKE_BUILD_TYPE=Debug -S . -B "${{ runner.temp }}/build/debug" -Dmun_build_examples=ON -Dmun_build_tests=ON -Dmun_binaries_path="${{ github.workspace }}/target/debug/" -Dmun_examples_path="${{ github.workspace }}/examples"

      - name: Configure CMake (release)
        run: pixi run cmake -DCMAKE_BUILD_TYPE=Release -S . -B "${{ runner.temp }}/build/release" -Dmun_build_examples=ON -Dmun_build_tests=ON -Dmun_binaries_path="${{ github.workspace }}/target/debug/" -Dmun_examples_path="${{ github.workspace }}/examples"

      - name: Build (debug)
        run: pixi run cmake --build "${{ runner.temp }}/build/debug" --config Debug

      - name: Build (release)
        run: pixi run cmake --build "${{ runner.temp }}/build/release" --config Release

      - name: Test (debug)
        run: pixi run ctest --test-dir "${{ runner.temp }}/build/debug" -C Debug

      - name: Test (release)
        run: pixi run ctest --test-dir "${{ runner.temp }}/build/release" -C Release

  style:
    name: Check Style
    runs-on: ubuntu-22.04
    needs: check
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.10.1
        with:
          cache: true
          frozen: true

      - name: Install nightly rustfmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: rustup run nightly cargo fmt --all -- --check

      - name: Run cargo clippy
        run: pixi run clippy

      - name: Check generated files
        run: pixi run cargo test -p tools
